### ISSUE TITLE
Error running Terraform apply

### ISSUE THREAD

**Issue by Amir-Souri01** [devopshobbies/terraform-tutorial#13]
Hi
I got this error when I want to run my script in terraform for t2.micro in us-east-1.

Error: Error launching source instance: VPCIdNotSpecified: No default VPC for this user. GroupName is only supported for EC2-Classic and default VPC.

**Comment by mehdi-ra** [comment]
Hi :hand: 
Try to search before opening the issue on the repository but anyway, I found a similar problem on the stack overflow. Check and keep me in touch if the problem is not resolved yet.

Link to [stack overflow](https://stackoverflow.com/questions/67973518/terraform-simple-script-says-error-error-launching-source-instance-vpcidnotsp).

```
As the error suggests, it doesn't find the default VPC in the us-east-1 region. You can provide the subnet_id within your VPC to create your instance as below.

 resource "aws_instance" "ec2demo" {
           ami           = "ami-c998b6b2" 
           instance_type = "t2.micro"
           subnet_id = "subnet-0b1250d733767bafe"
  }

```

**Comment by Amir-Souri01** [comment]
Thank you Mehdi, it works
